FROM golang:1.9.6-alpine3.7


ENV GOPATH /gopath
ENV ROUTER  ${GOPATH}/src/github.com/emphant/redis-mulive-router
ENV PATH   ${GOPATH}/bin:${PATH}:${CODIS}/bin
COPY . ${ROUTER}

RUN apk update && apk add  autoconf make

RUN make -C ${ROUTER} distclean
RUN make -C ${ROUTER} build
RUN make -C ${ROUTER} install
RUN make -C ${ROUTER} cleardir


