apiVersion: v1
kind: Service
metadata:
  name: rds-router
  labels:
    app: rds-router
  namespace: emphant
spec:
  ports:
    # the port that this service should serve on
  - port: 29000
    targetPort: 29000
  - port: 21080
    targetPort: 21080
  selector:
    app: rds-router